# Generated by Django 5.0.4 on 2024-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=160, verbose_name='name')),
                ('body', models.CharField(default='YOUR BODY HERE', max_length=600, verbose_name='Body')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
